{
  "url": "https://api.github.com/repos/facebook/react/issues/12262",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/12262/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/12262/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/12262/events",
  "html_url": "https://github.com/facebook/react/issues/12262",
  "id": 299021172,
  "node_id": "MDU6SXNzdWUyOTkwMjExNzI=",
  "number": 12262,
  "title": "componentDidCatch unhandled?",
  "user": {
    "login": "TanninOne",
    "id": 8525754,
    "node_id": "MDQ6VXNlcjg1MjU3NTQ=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/8525754?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/TanninOne",
    "html_url": "https://github.com/TanninOne",
    "followers_url": "https://api.github.com/users/TanninOne/followers",
    "following_url": "https://api.github.com/users/TanninOne/following{/other_user}",
    "gists_url": "https://api.github.com/users/TanninOne/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/TanninOne/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/TanninOne/subscriptions",
    "organizations_url": "https://api.github.com/users/TanninOne/orgs",
    "repos_url": "https://api.github.com/users/TanninOne/repos",
    "events_url": "https://api.github.com/users/TanninOne/events{/privacy}",
    "received_events_url": "https://api.github.com/users/TanninOne/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 2,
  "created_at": "2018-02-21T15:46:30Z",
  "updated_at": "2018-02-22T10:57:40Z",
  "closed_at": "2018-02-21T16:12:19Z",
  "author_association": "NONE",
  "body": "**Do you want to request a *feature* or report a *bug*?**\r\n\r\nNot sure tbh.\r\n\r\n**What is the current behavior?**\r\n\r\nI have global handler for unhandled errors:\r\nwindow.addEventListener('error', (evt) => ...)\r\n\r\nNow when I use the componentDidCatch function it gets called correctly when render throws an exception but that global error event is also triggered - and before the componentDidCatch call.\r\n\r\n**What is the expected behavior?**\r\n\r\nSince componentDidCatch handles the error I'd prefer if the global event wasn't triggered, same as with a usual try-catch block.\r\n\r\nOr is there at least some way to  figure out from the evt object in the event handler that the exception is caught by react?\r\n\r\nI hope this made sense...",
  "closed_by": {
    "login": "gaearon",
    "id": 810438,
    "node_id": "MDQ6VXNlcjgxMDQzOA==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/810438?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gaearon",
    "html_url": "https://github.com/gaearon",
    "followers_url": "https://api.github.com/users/gaearon/followers",
    "following_url": "https://api.github.com/users/gaearon/following{/other_user}",
    "gists_url": "https://api.github.com/users/gaearon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gaearon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gaearon/subscriptions",
    "organizations_url": "https://api.github.com/users/gaearon/orgs",
    "repos_url": "https://api.github.com/users/gaearon/repos",
    "events_url": "https://api.github.com/users/gaearon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gaearon/received_events",
    "type": "User",
    "site_admin": false
  }
}
