{
  "url": "https://api.github.com/repos/facebook/react/issues/13053",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/13053/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/13053/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/13053/events",
  "html_url": "https://github.com/facebook/react/issues/13053",
  "id": 332788435,
  "node_id": "MDU6SXNzdWUzMzI3ODg0MzU=",
  "number": 13053,
  "title": "React 16.4.1 TS2339: Property 'createContext' does not exist on type 'typeof React'.",
  "user": {
    "login": "Rufix",
    "id": 11018478,
    "node_id": "MDQ6VXNlcjExMDE4NDc4",
    "avatar_url": "https://avatars3.githubusercontent.com/u/11018478?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Rufix",
    "html_url": "https://github.com/Rufix",
    "followers_url": "https://api.github.com/users/Rufix/followers",
    "following_url": "https://api.github.com/users/Rufix/following{/other_user}",
    "gists_url": "https://api.github.com/users/Rufix/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Rufix/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Rufix/subscriptions",
    "organizations_url": "https://api.github.com/users/Rufix/orgs",
    "repos_url": "https://api.github.com/users/Rufix/repos",
    "events_url": "https://api.github.com/users/Rufix/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Rufix/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 7,
  "created_at": "2018-06-15T14:08:28Z",
  "updated_at": "2018-07-12T00:38:44Z",
  "closed_at": "2018-06-15T14:39:16Z",
  "author_association": "NONE",
  "body": "Hello there,\r\n\r\nKinda new to React, trying to delve a bit into Contexts, however the aforementioned method refuses to exist.  \r\n\r\n```\r\nimport * as React from \"react\";\r\n\r\nexport const UrlEditContext = React.createContext(new UrlViewItem());\r\n```\r\n\r\nThis is really all the code I've got on this. This happens both with React 16.4.1 and 16.3.2. Other React libraries I have:\r\n\r\nreact-dom 16.0.0\r\nreact-hot-loader 3.0.0-beta.7 (came with the project created with Visual Studio)\r\nreact-router-dom 4.1.1\r\n\r\nTypescript's version's 2.4.1.\r\n\r\nAnyone has any idea why would I receive the aforementioned error? Google and SO have literally (yes, literally) nothing on the topic.\r\n\r\nThanks,\r\nHuggy",
  "closed_by": {
    "login": "gaearon",
    "id": 810438,
    "node_id": "MDQ6VXNlcjgxMDQzOA==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/810438?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gaearon",
    "html_url": "https://github.com/gaearon",
    "followers_url": "https://api.github.com/users/gaearon/followers",
    "following_url": "https://api.github.com/users/gaearon/following{/other_user}",
    "gists_url": "https://api.github.com/users/gaearon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gaearon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gaearon/subscriptions",
    "organizations_url": "https://api.github.com/users/gaearon/orgs",
    "repos_url": "https://api.github.com/users/gaearon/repos",
    "events_url": "https://api.github.com/users/gaearon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gaearon/received_events",
    "type": "User",
    "site_admin": false
  }
}
