{
  "url": "https://api.github.com/repos/facebook/react/issues/13322",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/13322/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/13322/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/13322/events",
  "html_url": "https://github.com/facebook/react/issues/13322",
  "id": 347591444,
  "node_id": "MDU6SXNzdWUzNDc1OTE0NDQ=",
  "number": 13322,
  "title": "Error Handling ",
  "user": {
    "login": "rahuls321",
    "id": 29652757,
    "node_id": "MDQ6VXNlcjI5NjUyNzU3",
    "avatar_url": "https://avatars2.githubusercontent.com/u/29652757?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rahuls321",
    "html_url": "https://github.com/rahuls321",
    "followers_url": "https://api.github.com/users/rahuls321/followers",
    "following_url": "https://api.github.com/users/rahuls321/following{/other_user}",
    "gists_url": "https://api.github.com/users/rahuls321/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rahuls321/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rahuls321/subscriptions",
    "organizations_url": "https://api.github.com/users/rahuls321/orgs",
    "repos_url": "https://api.github.com/users/rahuls321/repos",
    "events_url": "https://api.github.com/users/rahuls321/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rahuls321/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 1,
  "created_at": "2018-08-04T06:03:43Z",
  "updated_at": "2018-08-06T15:10:31Z",
  "closed_at": "2018-08-06T15:10:30Z",
  "author_association": "NONE",
  "body": "\r\n**Difficult to Handle such kind of error !!**\r\n\r\nIt's very difficult to find out the bug whenever by mistake I use curly braces instead of parenthesis then console showing an error but not able to find out in which file you got error rather it shows the main building block file. ",
  "closed_by": {
    "login": "gaearon",
    "id": 810438,
    "node_id": "MDQ6VXNlcjgxMDQzOA==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/810438?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gaearon",
    "html_url": "https://github.com/gaearon",
    "followers_url": "https://api.github.com/users/gaearon/followers",
    "following_url": "https://api.github.com/users/gaearon/following{/other_user}",
    "gists_url": "https://api.github.com/users/gaearon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gaearon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gaearon/subscriptions",
    "organizations_url": "https://api.github.com/users/gaearon/orgs",
    "repos_url": "https://api.github.com/users/gaearon/repos",
    "events_url": "https://api.github.com/users/gaearon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gaearon/received_events",
    "type": "User",
    "site_admin": false
  }
}
