{
  "url": "https://api.github.com/repos/facebook/react/issues/4910",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/4910/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/4910/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/4910/events",
  "html_url": "https://github.com/facebook/react/issues/4910",
  "id": 107257838,
  "node_id": "MDU6SXNzdWUxMDcyNTc4Mzg=",
  "number": 4910,
  "title": "Confusing stack traces for exceptions in render",
  "user": {
    "login": "wonnage",
    "id": 125177,
    "node_id": "MDQ6VXNlcjEyNTE3Nw==",
    "avatar_url": "https://avatars3.githubusercontent.com/u/125177?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/wonnage",
    "html_url": "https://github.com/wonnage",
    "followers_url": "https://api.github.com/users/wonnage/followers",
    "following_url": "https://api.github.com/users/wonnage/following{/other_user}",
    "gists_url": "https://api.github.com/users/wonnage/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/wonnage/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/wonnage/subscriptions",
    "organizations_url": "https://api.github.com/users/wonnage/orgs",
    "repos_url": "https://api.github.com/users/wonnage/repos",
    "events_url": "https://api.github.com/users/wonnage/events{/privacy}",
    "received_events_url": "https://api.github.com/users/wonnage/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 2,
  "created_at": "2015-09-18T18:56:37Z",
  "updated_at": "2015-09-22T01:33:17Z",
  "closed_at": "2015-09-22T01:33:17Z",
  "author_association": "NONE",
  "body": "I put a `throw` inside of a render function, and got this stacktrace:\n\n```\nError caught: TypeError: Cannot read property '_currentElement' of null\n    at ReactCompositeComponentMixin._updateRenderedComponent (https://localhost/vendor.js:19381:53)\n    at ReactCompositeComponentMixin._performComponentUpdate (https://localhost/vendor.js:19363:11)\n    at ReactCompositeComponentMixin.updateComponent (https://localhost/vendor.js:19279:13)\n    at ReactPerf.measure.wrapper [as updateComponent] (https://localhost/vendor.js:11015:22)\n    at ReactCompositeComponentMixin.receiveComponent (https://localhost/vendor.js:19143:11)\n    at Object.ReactReconciler.receiveComponent (https://localhost/vendor.js:11151:23)\n   ...\n```\n\nNone of this is code I wrote, and none of this points to the component that failed. I'm using ES6 classes instead of React.createClass, which may or may not be relevant.\n",
  "closed_by": {
    "login": "sophiebits",
    "id": 6820,
    "node_id": "MDQ6VXNlcjY4MjA=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/6820?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/sophiebits",
    "html_url": "https://github.com/sophiebits",
    "followers_url": "https://api.github.com/users/sophiebits/followers",
    "following_url": "https://api.github.com/users/sophiebits/following{/other_user}",
    "gists_url": "https://api.github.com/users/sophiebits/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/sophiebits/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/sophiebits/subscriptions",
    "organizations_url": "https://api.github.com/users/sophiebits/orgs",
    "repos_url": "https://api.github.com/users/sophiebits/repos",
    "events_url": "https://api.github.com/users/sophiebits/events{/privacy}",
    "received_events_url": "https://api.github.com/users/sophiebits/received_events",
    "type": "User",
    "site_admin": false
  }
}
