{
  "url": "https://api.github.com/repos/facebook/react/issues/8352",
  "repository_url": "https://api.github.com/repos/facebook/react",
  "labels_url": "https://api.github.com/repos/facebook/react/issues/8352/labels{/name}",
  "comments_url": "https://api.github.com/repos/facebook/react/issues/8352/comments",
  "events_url": "https://api.github.com/repos/facebook/react/issues/8352/events",
  "html_url": "https://github.com/facebook/react/issues/8352",
  "id": 190425237,
  "node_id": "MDU6SXNzdWUxOTA0MjUyMzc=",
  "number": 8352,
  "title": "ReactDOM: TypeError: console.debug is not a function",
  "user": {
    "login": "KevinNorth",
    "id": 2762511,
    "node_id": "MDQ6VXNlcjI3NjI1MTE=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/2762511?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/KevinNorth",
    "html_url": "https://github.com/KevinNorth",
    "followers_url": "https://api.github.com/users/KevinNorth/followers",
    "following_url": "https://api.github.com/users/KevinNorth/following{/other_user}",
    "gists_url": "https://api.github.com/users/KevinNorth/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/KevinNorth/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/KevinNorth/subscriptions",
    "organizations_url": "https://api.github.com/users/KevinNorth/orgs",
    "repos_url": "https://api.github.com/users/KevinNorth/repos",
    "events_url": "https://api.github.com/users/KevinNorth/events{/privacy}",
    "received_events_url": "https://api.github.com/users/KevinNorth/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [

  ],
  "state": "closed",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 6,
  "created_at": "2016-11-18T21:24:13Z",
  "updated_at": "2016-11-28T18:23:39Z",
  "closed_at": "2016-11-21T18:23:02Z",
  "author_association": "NONE",
  "body": "I am experiencing the following bug using React 15.4.0 and React-DOM 15.4.0.\r\n\r\nWhen I run my team's test suite, which uses Mocha 2.5.3, the following exception is thrown and Mocha crashes without running the tests:\r\n\r\n```\r\nTypeError: console.debug is not a function\r\n    at Object.<anonymous> (<our project's directory>/node_modules/react-dom/lib/ReactDOM.js:73:17)\r\n    at Module._compile (module.js:573:32)\r\n    at Module._extensions..js (module.js:582:10)\r\n    at Object.require.extensions.(anonymous function) [as .js] (<our project's directory>/node_modules/babel-register/lib/node.js:152:7)\r\n    at Module.load (module.js:490:32)\r\n    at tryModuleLoad (module.js:449:12)\r\n    at Function.Module._load (module.js:441:3)\r\n    at Module.require (module.js:500:17)\r\n    at require (internal/module.js:20:19)\r\n    at Object.<anonymous> (<our project's directory>/node_modules/react-dom/index.js:3:18)\r\n    at Module._compile (module.js:573:32)\r\n    at Module._extensions..js (module.js:582:10)\r\n    at Object.require.extensions.(anonymous function) [as .js] (/<our project's directory>/node_modules/babel-register/lib/node.js:152:7)\r\n    at Module.load (module.js:490:32)\r\n    at tryModuleLoad (module.js:449:12)\r\n    at Function.Module._load (module.js:441:3)\r\n    at Module.require (module.js:500:17)\r\n    at require (internal/module.js:20:19)\r\n    at Object.<anonymous> (<our project's directory>/node_modules/react-widgets/lib/util/compat.js:7:17)\r\n    at Module._compile (module.js:573:32)\r\n    at Module._extensions..js (module.js:582:10)\r\n    at Object.require.extensions.(anonymous function) [as .js] (<our project's directory>/node_modules/babel-register/lib/node.js:152:7)\r\n    at Module.load (module.js:490:32)\r\n    at tryModuleLoad (module.js:449:12)\r\n    at Function.Module._load (module.js:441:3)\r\n    at Module.require (module.js:500:17)\r\n    at require (internal/module.js:20:19)\r\n    at Object.<anonymous> (<our project's directory>/node_modules/react-widgets/lib/Popup.js:37:15)\r\n    at Module._compile (module.js:573:32)\r\n    at Module._extensions..js (module.js:582:10)\r\n    at Object.require.extensions.(anonymous function) [as .js] (<our project's directory>/node_modules/babel-register/lib/node.js:152:7)\r\n    at Module.load (module.js:490:32)\r\n    at tryModuleLoad (module.js:449:12)\r\n    at Function.Module._load (module.js:441:3)\r\n    at Module.require (module.js:500:17)\r\n    at require (internal/module.js:20:19)\r\n    at Object.<anonymous> (<our project's directory>/node_modules/react-widgets/lib/DropdownList.js:45:14)\r\n    at Module._compile (module.js:573:32)\r\n    at Module._extensions..js (module.js:582:10)\r\n    at Object.require.extensions.(anonymous function) [as .js] (<our project's directory>/node_modules/babel-register/lib/node.js:152:7)\r\n    at Module.load (module.js:490:32)\r\n    at tryModuleLoad (module.js:449:12)\r\n    at Function.Module._load (module.js:441:3)\r\n    at Module.require (module.js:500:17)\r\n    at require (internal/module.js:20:19)\r\n    at Object.<anonymous> (<one of our own source code files>)\r\n    at Module._compile (module.js:573:32)\r\n    at loader (<our project's directory>/node_modules/babel-register/lib/node.js:144:5)\r\n    at Object.require.extensions.(anonymous function) [as .js] (<our project's directory>/node_modules/babel-register/lib/node.js:154:7)\r\n    at Module.load (module.js:490:32)\r\n    at tryModuleLoad (module.js:449:12)\r\n    at Function.Module._load (module.js:441:3)\r\n    at Module.require (module.js:500:17)\r\n    at require (internal/module.js:20:19)\r\n    at Object.<anonymous> (<our project's directory>/index.js:xx:xx)\r\n    at Module._compile (module.js:573:32)\r\n    at loader (<our project's directory>/node_modules/babel-register/lib/node.js:144:5)\r\n    at Object.require.extensions.(anonymous function) [as .js] (<our project's directory>/node_modules/babel-register/lib/node.js:154:7)\r\n    at Module.load (module.js:490:32)\r\n    at tryModuleLoad (module.js:449:12)\r\n    at Function.Module._load (module.js:441:3)\r\n    at Module.require (module.js:500:17)\r\n    at require (internal/module.js:20:19)\r\n    at Object.<anonymous> (<one of our own source code files>)\r\n    at Module._compile (module.js:573:32)\r\n    at loader (<our project's directory>/node_modules/babel-register/lib/node.js:144:5)\r\n    at Object.require.extensions.(anonymous function) [as .js] (<our project's directory>/node_modules/babel-register/lib/node.js:154:7)\r\n    at Module.load (module.js:490:32)\r\n    at tryModuleLoad (module.js:449:12)\r\n    at Function.Module._load (module.js:441:3)\r\n    at Module.require (module.js:500:17)\r\n    at require (internal/module.js:20:19)\r\n    at Object.<anonymous> (<one of our own source code files>)\r\n    at Module._compile (module.js:573:32)\r\n    at loader (<our project's directory>/node_modules/babel-register/lib/node.js:144:5)\r\n    at Object.require.extensions.(anonymous function) [as .js] (<our project's directory>/node_modules/babel-register/lib/node.js:154:7)\r\n    at Module.load (module.js:490:32)\r\n    at tryModuleLoad (module.js:449:12)\r\n    at Function.Module._load (module.js:441:3)\r\n    at Module.require (module.js:500:17)\r\n    at require (internal/module.js:20:19)\r\n    at Object.<anonymous> (<our project's directory>/src/routes.js:1:1)\r\n    at Module._compile (module.js:573:32)\r\n    at loader (<our project's directory>/node_modules/babel-register/lib/node.js:144:5)\r\n    at Object.require.extensions.(anonymous function) [as .js] (<our project's directory>/node_modules/babel-register/lib/node.js:154:7)\r\n    at Module.load (module.js:490:32)\r\n    at tryModuleLoad (module.js:449:12)\r\n    at Function.Module._load (module.js:441:3)\r\n    at Module.require (module.js:500:17)\r\n    at require (internal/module.js:20:19)\r\n    at Object.<anonymous> (<one of our own test files>)\r\n    at Module._compile (module.js:573:32)\r\n    at loader (<our project's directory>/babel-register/lib/node.js:144:5)\r\n    at Object.require.extensions.(anonymous function) [as .js] (<our project's directory>node_modules/babel-register/lib/node.js:154:7)\r\n    at Module.load (module.js:490:32)\r\n    at tryModuleLoad (module.js:449:12)\r\n    at Function.Module._load (module.js:441:3)\r\n    at Module.require (module.js:500:17)\r\n    at require (internal/module.js:20:19)\r\n    at <our project's directory>node_modules/mocha/lib/mocha.js:220:27\r\n    at Array.forEach (native)\r\n    at Mocha.loadFiles (<our project's directory>/node_modules/mocha/lib/mocha.js:217:14)\r\n    at Mocha.run (<our project's directory>/node_modules/mocha/lib/mocha.js:469:10)\r\n    at Object.<anonymous> (<our project's directory>/node_modules/mocha/bin/_mocha:404:18)\r\n    at Module._compile (module.js:573:32)\r\n    at Object.Module._extensions..js (module.js:582:10)\r\n    at Module.load (module.js:490:32)\r\n    at tryModuleLoad (module.js:449:12)\r\n    at Function.Module._load (module.js:441:3)\r\n    at Module.runMain (module.js:607:10)\r\n    at run (bootstrap_node.js:420:7)\r\n    at startup (bootstrap_node.js:139:9)\r\n    at bootstrap_node.js:535:3\r\n```\r\n\r\nLooking at the stack trace, the error is coming from `react-dom/lib/ReactDOM.js` on line 73. This is the code at and surrounding that line:\r\n\r\n```\r\n    // First check if devtools is not installed\r\n    if (typeof __REACT_DEVTOOLS_GLOBAL_HOOK__ === 'undefined') {\r\n      // If we're in Chrome or Firefox, provide a download link if not installed.\r\n      if (navigator.userAgent.indexOf('Chrome') > -1 && navigator.userAgent.indexOf('Edge') === -1 || navigator.userAgent.indexOf('Firefox') > -1) {\r\n        // Firefox does not have the issue with devtools loaded over file://\r\n        var showFileUrlMessage = window.location.protocol.indexOf('http') === -1 && navigator.userAgent.indexOf('Firefox') === -1;\r\n        console.debug('Download the React DevTools ' + (showFileUrlMessage ? 'and use an HTTP server (instead of a file: URL) ' : '') + 'for a better development experience: ' + 'https://fb.me/react-devtools');\r\n      }\r\n    }\r\n```\r\n\r\nThis code calls `console.debug()`. The exception message makes it seem like `console.debug` is not a function that Node.js believes exists, and in fact, [the documentation for Node.js' `console` shows that it has no `debug()` function](https://nodejs.org/api/console.html).\r\n\r\nInterestingly, running my team's project works fine - the only time I see this exception is when I try to run my test suite.",
  "closed_by": {
    "login": "gaearon",
    "id": 810438,
    "node_id": "MDQ6VXNlcjgxMDQzOA==",
    "avatar_url": "https://avatars0.githubusercontent.com/u/810438?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gaearon",
    "html_url": "https://github.com/gaearon",
    "followers_url": "https://api.github.com/users/gaearon/followers",
    "following_url": "https://api.github.com/users/gaearon/following{/other_user}",
    "gists_url": "https://api.github.com/users/gaearon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gaearon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gaearon/subscriptions",
    "organizations_url": "https://api.github.com/users/gaearon/orgs",
    "repos_url": "https://api.github.com/users/gaearon/repos",
    "events_url": "https://api.github.com/users/gaearon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gaearon/received_events",
    "type": "User",
    "site_admin": false
  }
}
